### ISSUE TITLE
Rename xmlchange_cmnds file to shell_commands

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ptclm#7]
The file `mydatafiles/1x1pt_US-UMB/xmlchange_cmnds` should be renamed to `shell_commands` in order to let us move ahead with https://github.com/ESMCI/cime/issues/763.

**Comment by ekluzek** [comment]
This actually doesn't matter, since this file is just the checked in results of an older version of PTCLM. But, I am fixing it anyway.

**Comment by ekluzek** [comment]
Fixed in PTCLM2_20200121
